### ISSUE TITLE
Loadbalancer

### ISSUE THREAD

**Issue by czebe** [logux/logux-server#52]
How does this work in a load balanced environment?

**Comment by ai** [comment]
Great question :). This architecture will allow you to use any simple load balance strategies (like connect the new user to a random server)

1. It will work great if you will not store any important data in Logux server memory. All important data should be stored in Redis, PostgreSQL/MySQL or any other central DB.
2. You will use Redux or any broadcast system to resend new action from one server to other and call `server.sendAction(action, meta)` on all other servers. So when a client will send the new action to server A, server A will apply the action (save the result to DB) and then send the new action to server B and C, servers B and C will send this action to all clients subscribed to a specific channel.

This is the best simplest strategy. But when you have too many actions, it could create a big load on the servers (since all servers will receive all actions).

**Comment by ai** [comment]
When you will have more actions you may want to have the smarter way: You will remove “send all actions to all servers and pass it to `sendAction`” code and replace it with:

1. You still have Redis to sync actions between all servers. But instead of having one channel to send all actions you have separated channels for every Logux channel.
2. When users ask the server to subscribe they to some channel, the server applies own subscription in the channel on the Redis.
3. When the server receives an action, it will send it also to Redis channel.
4. When the server receives action from another server by Redis, this server will call `sendAction` for this new action.
5. If your action could have multiple channels you need to prevent calling `sendAction` twice. But I just recommend having one channel per action.

In this system, you can still use any simple load balance strategies (like connect the new user to a random server).

**Comment by ai** [comment]
When you will have even more actions, you will need an even smarter system. And only in this case, you will need some specific load balancer.

You must send user ID (or some group ID) in web socket opening request (it may force you to write custom WS connection driver for Logux, but it is easy). According this user ID balancer will send the user to the specific server. As result, you will keep all users subscribed to some channel on the single server. So in most of cases servers will be free from receiving actions from Redis.

It is a complicated way (you need special WS connection driver and complex balancer), but you need this way only on really high load. In this case, you will have money for developers :D.

**Comment by ai** [comment]
What do you think about this plan? I am bad at describing something in English, feel free for additional questions.

**Comment by czebe** [comment]
Sounds good, thanks Andrey for elaborating on this!
Option 2 sounds feasible and even the custom loadbalancer makes sense. We're using Kafka for messaging, but Redis is also used. Will have to check how we integrate this with legacy Java apis -- a Java port perhaps? 😄

**Comment by ai** [comment]
Kafka or any message delivery system is reliable for 2 and 3 steps. I used Redis only as the most well-known tool for this :).

I recommend to add a Node.js proxy for Java in the beginning:

1. You have a very simple Node.js server with Logux.
2. Also, you have an HTTP server on this Logux Server (just use `http` module in the same `server.js`)
3. Firewall allow only internal connection to Logux HTTP. You will use it only to connect to Java.
4. On new action Logux server will send HTTP request to legacy Java backend.
5. When Java backend wants to add action to client’s log, it will send HTTP request to Logux server.

I am planing to write this simple Logux HTTP/WS proxy in next month (we need it for Ruby on Rails).
